# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-10 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.TextField()),
                ('user_settings', models.TextField()),
                ('deadlines', models.TextField()),
                ('username', models.CharField(default='anon', max_length=150)),
            ],
        ),
    ]
