# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-08 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='username',
            field=models.CharField(default='anon', max_length=150),
        ),
    ]
